import { Cinema, Movie, ShowTime } from "@/types";

export const MOCK_MOVIES: Movie[] = [
  {
    id: "dune-2",
    title: "Dune: Phần Hai",
    originalTitle: "Dune: Part Two",
    overview: "Paul Atreides hợp lực cùng Chani và tộc người Fremen để trả thù những kẻ đã hủy diệt gia tộc anh. Đứng trước sự lựa chọn giữa tình yêu của đời mình và số phận của vũ trụ, anh phải ngăn chặn một tương lai tăm tối mà chỉ anh có thể nhìn thấy trước.",
    posterPath: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2024-03-01",
    voteAverage: 8.8,
    voteCount: 12450,
    genres: ["Khoa học viễn tưởng", "Hành động", "Phiêu lưu"],
    durationMinutes: 166,
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem", "Austin Butler"],
    trailerYoutubeId: "Way9Dexny3w",
    ageRating: "T16",
    status: "now_playing",
  },
  {
    id: "oppenheimer",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    overview: "Câu chuyện lịch sử kịch tính về cuộc đời của nhà vật lý lý thuyết J. Robert Oppenheimer, người đứng đầu Dự án Manhattan phát triển vũ khí nguyên tử đầu tiên trong Thế chiến thứ hai.",
    posterPath: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2023-07-21",
    voteAverage: 8.9,
    voteCount: 19800,
    genres: ["Tiểu sử", "Chính kịch", "Lịch sử"],
    durationMinutes: 180,
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr.", "Florence Pugh"],
    trailerYoutubeId: "uYPbbksJxIg",
    ageRating: "T18",
    status: "trending",
  },
  {
    id: "exhuma",
    title: "Quật Mộ Trùng Ma",
    originalTitle: "Exhuma",
    overview: "Sau khi liên tiếp gặp phải các sự kiện kỳ bí đe dọa sinh mạng của đứa con mới chào đời, một gia đình giàu có ở Los Angeles đã liên hệ với bộ đôi pháp sư trẻ nổi tiếng Hwa-rim và Bong-gil để cứu đứa bé. Cả nhóm tiến hành khai quật một ngôi mộ bí ẩn tại một vùng hẻo lánh của Hàn Quốc, vô tình giải phóng một thế lực tà ác đáng sợ.",
    posterPath: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2024-03-15",
    voteAverage: 8.4,
    voteCount: 8200,
    genres: ["Kinh dị", "Bí ẩn", "Giật gân"],
    durationMinutes: 134,
    director: "Jang Jae-hyun",
    cast: ["Choi Min-sik", "Kim Go-eun", "Yoo Hae-jin", "Lee Do-hyun"],
    trailerYoutubeId: "dffkY6y8K4o",
    ageRating: "T18",
    status: "now_playing",
  },
  {
    id: "inside-out-2",
    title: "Những Mảnh Ghép Cảm Xúc 2",
    originalTitle: "Inside Out 2",
    overview: "Chào mừng sự trở lại của cô bé Riley khi bước vào lứa tuổi dậy thì hỗn loạn. Trụ sở Cảm xúc bất ngờ đón nhận những vị khách mới đầy rắc rối: Lo Âu (Anxiety), Ganh Tị (Envy), Xấu Hổ (Embarrassment) và Chán Nản (Ennui).",
    posterPath: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2024-06-14",
    voteAverage: 8.2,
    voteCount: 9500,
    genres: ["Hoạt hình", "Gia đình", "Hài kịch"],
    durationMinutes: 96,
    director: "Kelsey Mann",
    cast: ["Amy Poehler", "Maya Hawke", "Kensington Tallman", "Liza Lapira"],
    trailerYoutubeId: "LEjhY15eCx0",
    ageRating: "P",
    status: "now_playing",
  },
  {
    id: "deadpool-wolverine",
    title: "Deadpool & Wolverine",
    originalTitle: "Deadpool & Wolverine",
    overview: "Cơ quan Quản lý Phương sai Thời gian (TVA) lôi kéo gã phản anh hùng ngổ ngáo Wade Wilson vào một nhiệm vụ vũ trụ mới. Để cứu lấy thế giới của mình, anh buộc phải tìm cách hợp tác với một Wolverine đang chán đời.",
    posterPath: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2024-07-26",
    voteAverage: 8.5,
    voteCount: 16700,
    genres: ["Hành động", "Hài hước", "Khoa học viễn tưởng"],
    durationMinutes: 127,
    director: "Shawn Levy",
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin", "Matthew Macfadyen"],
    trailerYoutubeId: "73_1biulkYk",
    ageRating: "T18",
    status: "trending",
  },
  {
    id: "interstellar",
    title: "Hố Đen Tử Thần",
    originalTitle: "Interstellar",
    overview: "Khi Trái Đất trong tương lai trở nên cạn kiệt tài nguyên và không thể sinh sống được nữa, một nhóm các nhà thám hiểm không gian dũng cảm thực hiện nhiệm vụ nguy hiểm nhất trong lịch sử nhân loại: du hành xuyên qua một lỗ sâu để tìm kiếm ngôi nhà mới cho nhân loại.",
    posterPath: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2014-11-07",
    voteAverage: 8.7,
    voteCount: 35000,
    genres: ["Khoa học viễn tưởng", "Chính kịch", "Phiêu lưu"],
    durationMinutes: 169,
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    trailerYoutubeId: "zSWdZVtXT7E",
    ageRating: "T13",
    status: "trending",
  },
  {
    id: "avatar-fire-ash",
    title: "Avatar 3: Lửa & Tro Tàn",
    originalTitle: "Avatar: Fire and Ash",
    overview: "Phần tiếp theo của siêu phẩm Pandora sẽ giới thiệu Tộc Người Tro (Ash People) - một bộ tộc Na'vi hung hãn, tôn thờ lửa và phản ánh mặt tối chưa từng thấy trên hành tinh Pandora.",
    posterPath: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2025-12-19",
    voteAverage: 9.0,
    voteCount: 4200,
    genres: ["Hành động", "Phiêu lưu", "Khoa học viễn tưởng"],
    durationMinutes: 190,
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Oona Chaplin"],
    trailerYoutubeId: "d9MyW72ELq0",
    ageRating: "T16",
    status: "upcoming",
  },
  {
    id: "lat-mat-7",
    title: "Lật Mặt 7: Một Điều Ước",
    originalTitle: "Face Off 7: One Wish",
    overview: "Bộ phim gia đình lấy đi nước mắt của hàng triệu khán giả Việt Nam của đạo diễn Lý Hải. Câu chuyện xoay quanh bà Hai 73 tuổi cùng 5 người con và câu hỏi nhức nhối: 'Khi mẹ già đi, ai sẽ là người chăm sóc mẹ?'.",
    posterPath: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2024-04-26",
    voteAverage: 8.9,
    voteCount: 18500,
    genres: ["Gia đình", "Chính kịch", "Tâm lý"],
    durationMinutes: 138,
    director: "Lý Hải",
    cast: ["Thanh Hiền", "Trương Minh Cường", "Đinh Y Nhung", "Quách Ngọc Tuyên"],
    trailerYoutubeId: "d7y-b6G-E1s",
    ageRating: "K",
    status: "now_playing",
  },
  {
    id: "mai",
    title: "Mai",
    originalTitle: "Mai",
    overview: "Mai - một phụ nữ làm nghề massage trị liệu gần 40 tuổi chịu nhiều tổn thương trong quá khứ, bất ngờ gặp gỡ Dương - chàng trai trẻ đào hoa mê nhạc. Mối tình chênh lệch tuổi tác đưa cả hai đối mặt với những định kiến nghiệt ngã của gia đình và số phận.",
    posterPath: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2024-02-10",
    voteAverage: 8.7,
    voteCount: 22000,
    genres: ["Tâm lý", "Lãng mạn", "Chính kịch"],
    durationMinutes: 131,
    director: "Trấn Thành",
    cast: ["Phương Anh Đào", "Tuấn Trần", "Trấn Thành", "Hồng Đào"],
    trailerYoutubeId: "z3uxX5nS5Yw",
    ageRating: "T18",
    status: "now_playing",
  },
  {
    id: "dao-pho-piano",
    title: "Đào, Phở và Piano",
    originalTitle: "Peach Blossom, Pho and Piano",
    overview: "Khắc họa vẻ đẹp hào hoa, bất khuất của người Hà Nội trong cuộc chiến đấu 60 ngày đêm mùa đông năm 1946 bảo vệ Thủ đô, thông qua câu chuyện tình lãng mạn giữa chàng tự vệ Dân và nàng tiểu thư Hà thành Thục Hương.",
    posterPath: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2024-02-10",
    voteAverage: 8.5,
    voteCount: 14200,
    genres: ["Lịch sử", "Chiến tranh", "Lãng mạn"],
    durationMinutes: 100,
    director: "Phi Tiến Sơn",
    cast: ["Doãn Quốc Đam", "Cao Thị Thùy Linh", "Trần Lực", "NSND Trung Hiếu"],
    trailerYoutubeId: "XQxK5Z9Q9l8",
    ageRating: "T13",
    status: "now_playing",
  },
  {
    id: "godzilla-x-kong",
    title: "Godzilla x Kong: Đế Chế Mới",
    originalTitle: "Godzilla x Kong: The New Empire",
    overview: "Sau trận quyết chiến tại Hong Kong, hai đại quái thú Godzilla và Kong buộc phải liên minh để đối đầu với một mối đe dọa khổng lồ chưa từng được khám phá đang ẩn sâu bên trong Trái Đất Rỗng (Hollow Earth).",
    posterPath: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&auto=format&fit=crop&q=80",
    backdropPath: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&auto=format&fit=crop&q=80",
    releaseDate: "2024-03-29",
    voteAverage: 8.3,
    voteCount: 15300,
    genres: ["Hành động", "Khoa học viễn tưởng", "Phiêu lưu"],
    durationMinutes: 115,
    director: "Adam Wingard",
    cast: ["Rebecca Hall", "Brian Tyree Henry", "Dan Stevens", "Kaylee Hottle"],
    trailerYoutubeId: "qqrpMRDuPfc",
    ageRating: "T13",
    status: "trending",
  }
];

export const MOCK_CINEMAS: Cinema[] = [
  {
    id: "beta-cinemas-xuan-thuy",
    name: "Beta Cinemas Xuân Thủy",
    address: "Tầng 4, Tòa nhà HITC, 239 Xuân Thủy, Cầu Giấy, Hà Nội",
    city: "Hà Nội",
  },
  {
    id: "cgv-vincom-ba-trieu",
    name: "CGV Vincom Center Bà Triệu",
    address: "Tầng 6, Vincom Center, 191 Bà Triệu, Hai Bà Trưng, Hà Nội",
    city: "Hà Nội",
  },
  {
    id: "lotte-cinema-keangnam",
    name: "Lotte Cinema Keangnam Landmark",
    address: "Tầng 5, Keangnam Landmark Tower, Phạm Hùng, Cầu Giấy, Hà Nội",
    city: "Hà Nội",
  },
  {
    id: "cgv-landmark-81",
    name: "CGV Vincom Landmark 81 (IMAX)",
    address: "Tầng B1, Landmark 81, 720A Điện Biên Phủ, P. 22, Bình Thạnh, TP.HCM",
    city: "TP. Hồ Chí Minh",
  },
  {
    id: "bhd-star-bitexco",
    name: "BHD Star Cineplex Bitexco",
    address: "Tầng 3 & 4, Bitexco Financial Tower, Quận 1, TP.HCM",
    city: "TP. Hồ Chí Minh",
  },
];

function getTodayInVietnam(): string {
  return new Date(Date.now() + 7 * 3_600_000).toISOString().slice(0, 10);
}

function shiftDays(baseDate: string, days: number): string {
  const [year, month, day] = baseDate.split("-").map(Number);
  return new Date(Date.UTC(year, month - 1, day + days)).toISOString().slice(0, 10);
}

const todayVN = getTodayInVietnam();
const tomorrowVN = shiftDays(todayVN, 1);
const dayAfterVN = shiftDays(todayVN, 2);

export const MOCK_SHOWTIMES: ShowTime[] = [
  // Suất chiếu hôm nay (todayVN)
  {
    id: "st-beta-today-1",
    movieId: "dune-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 01 (Dolby 7.1)",
    format: "2D Phụ Đề",
    date: todayVN,
    time: "20:30",
  },
  {
    id: "st-beta-today-2",
    movieId: "inside-out-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 02 (Laser HD)",
    format: "2D Lồng Tiếng",
    date: todayVN,
    time: "21:00",
  },
  {
    id: "st-beta-today-3",
    movieId: "exhuma",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 03 (Standard)",
    format: "2D Phụ Đề",
    date: todayVN,
    time: "20:45",
  },

  // Suất chiếu ngày mai (tomorrowVN) - Phòng Beta 01 (Dolby 7.1)
  {
    id: "st-beta-1",
    movieId: "dune-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 01 (Dolby 7.1)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "09:30",
  },
  {
    id: "st-beta-7",
    movieId: "oppenheimer",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 01 (Dolby 7.1)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "12:45",
  },
  {
    id: "st-beta-4",
    movieId: "exhuma",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 01 (Dolby 7.1)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "16:15",
  },
  {
    id: "st-beta-1b",
    movieId: "dune-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 01 (Dolby 7.1)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "19:30",
  },

  // Suất chiếu ngày mai (tomorrowVN) - Phòng Beta 02 (Laser HD)
  {
    id: "st-beta-8",
    movieId: "deadpool-wolverine",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 02 (Laser HD)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "14:00",
  },
  {
    id: "st-beta-5",
    movieId: "inside-out-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 02 (Laser HD)",
    format: "2D Lồng Tiếng",
    date: tomorrowVN,
    time: "16:40",
  },
  {
    id: "st-beta-2",
    movieId: "dune-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 02 (Laser HD)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "18:45",
  },
  {
    id: "st-beta-8b",
    movieId: "deadpool-wolverine",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 02 (Laser HD)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "22:00",
  },

  // Suất chiếu ngày mai (tomorrowVN) - Phòng Beta 03 (Standard)
  {
    id: "st-beta-3",
    movieId: "exhuma",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 03 (Standard)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "13:30",
  },
  {
    id: "st-beta-6",
    movieId: "inside-out-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 03 (Standard)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "16:15",
  },
  {
    id: "st-beta-3b",
    movieId: "exhuma",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 03 (Standard)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "18:20",
  },
  {
    id: "st-beta-6b",
    movieId: "inside-out-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 03 (Standard)",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "21:05",
  },

  // Suất chiếu ngày kia (dayAfterVN)
  {
    id: "st-beta-dayafter-1",
    movieId: "dune-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 01 (Dolby 7.1)",
    format: "2D Phụ Đề",
    date: dayAfterVN,
    time: "19:00",
  },
  {
    id: "st-beta-dayafter-2",
    movieId: "inside-out-2",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 02 (Laser HD)",
    format: "2D Lồng Tiếng",
    date: dayAfterVN,
    time: "17:30",
  },

  // Các rạp khác
  {
    id: "st-1",
    movieId: "dune-2",
    cinemaId: "cgv-landmark-81",
    cinemaName: "CGV Vincom Landmark 81",
    roomName: "Phòng IMAX Laser 01",
    format: "IMAX Laser",
    date: tomorrowVN,
    time: "18:30",
  },
  {
    id: "st-3",
    movieId: "dune-2",
    cinemaId: "cgv-vincom-ba-trieu",
    cinemaName: "CGV Vincom Center Bà Triệu",
    roomName: "Phòng Cinema 03",
    format: "2D Phụ Đề",
    date: tomorrowVN,
    time: "19:00",
  },
  {
    id: "st-5",
    movieId: "inside-out-2",
    cinemaId: "lotte-cinema-keangnam",
    cinemaName: "Lotte Cinema Keangnam Landmark",
    roomName: "Phòng Family 01",
    format: "2D Lồng Tiếng",
    date: tomorrowVN,
    time: "17:15",
  },
  {
    id: "st-latmat7-1",
    movieId: "lat-mat-7",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 01 (Dolby 7.1)",
    format: "2D Phụ Đề",
    date: todayVN,
    time: "17:00",
  },
  {
    id: "st-mai-1",
    movieId: "mai",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 02 (Laser HD)",
    format: "2D Phụ Đề",
    date: todayVN,
    time: "18:00",
  },
  {
    id: "st-daopho-1",
    movieId: "dao-pho-piano",
    cinemaId: "beta-cinemas-xuan-thuy",
    cinemaName: "Beta Cinemas Xuân Thủy",
    roomName: "Phòng Beta 03 (Standard)",
    format: "2D Phụ Đề",
    date: todayVN,
    time: "16:00",
  },
  {
    id: "st-godzilla-1",
    movieId: "godzilla-x-kong",
    cinemaId: "cgv-landmark-81",
    cinemaName: "CGV Vincom Landmark 81",
    roomName: "Phòng IMAX Laser 01",
    format: "IMAX Laser",
    date: tomorrowVN,
    time: "20:00",
  },
];

export const POPCORN_FLAVOR_OPTIONS = [
  { id: "sweet", name: "Bắp Ngọt Truyền Thống", extra: 0, tag: "Miễn phí" },
  { id: "salted", name: "Bắp Mặn Bơ Tỏi", extra: 0, tag: "Miễn phí" },
  { id: "cheese", name: "Bắp Lắc Phô Mai", extra: 10000, tag: "+10.000đ" },
  { id: "caramel", name: "Bắp Caramel Cháy", extra: 10000, tag: "+10.000đ" },
] as const;

export const DRINK_TYPE_OPTIONS = [
  { id: "pepsi", name: "Pepsi Black", tag: "Gas mát lạnh" },
  { id: "7up", name: "7Up Chanh Tươi", tag: "Sảng khoái" },
  { id: "mirinda", name: "Mirinda Cam", tag: "Ngọt ngào" },
  { id: "peach_tea", name: "Trà Đào Cam Sả", tag: "Thanh mát", extra: 5000 },
] as const;

export const DRINK_SIZE_OPTIONS = [
  { id: "regular", name: "Ly Tiêu Chuẩn (22oz)", extra: 0 },
  { id: "large", name: "Ly Khổng Lồ (32oz)", extra: 12000, tag: "+12.000đ" },
] as const;

export const CONCESSION_COMBOS = [
  {
    id: "combo-beta-solo",
    name: "Combo Beta Solo (1 Bắp + 1 Nước)",
    description: "1 Bắp rang bơ 60oz (tùy chọn vị) + 1 Nước ngọt lớn 22oz (tự chọn vị/cỡ)",
    price: 59000,
    icon: "🍿",
    popcornSlots: 1,
    drinkSlots: 1,
    badge: "Bán chạy nhất",
  },
  {
    id: "combo-beta-couple",
    name: "Combo Beta Couple Đôi Bạn (Bắp 2 Ngăn + 2 Nước)",
    description: "1 Bắp khổng lồ 2 ngăn 85oz (mix 2 vị độc đáo) + 2 Nước ngọt lớn 22oz",
    price: 89000,
    icon: "🥤",
    popcornSlots: 2,
    drinkSlots: 2,
    badge: "Tiết kiệm 30%",
  },
  {
    id: "combo-beta-party",
    name: "Combo Beta Party Sinh Viên (2 Bắp + 3 Nước)",
    description: "2 Bắp rang bơ thơm lừng + 3 Nước ngọt lớn + 1 Xúc xích nướng phô mai cay",
    price: 129000,
    icon: "🌭",
    popcornSlots: 2,
    drinkSlots: 3,
    badge: "Nhóm 3-4 bạn",
  },
];
